//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_hienthi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HPE_ETCEntities : DbContext
    {
        public HPE_ETCEntities()
            : base("name=HPE_ETCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IN_CheckEtag> IN_CheckEtag { get; set; }
        public DbSet<IN_CheckForceOpen> IN_CheckForceOpen { get; set; }
        public DbSet<OUT_CheckEtag> OUT_CheckEtag { get; set; }
        public DbSet<OUT_CheckForceOpen> OUT_CheckForceOpen { get; set; }
        public DbSet<OUT_CheckSmartCard> OUT_CheckSmartCard { get; set; }
        public DbSet<IN_CheckSmartCard> IN_CheckSmartCard { get; set; }
    }
}
